version: 2
jobs:
  build-publish:
    machine:
      image: ubuntu-2004:202008-01
    steps:
      - checkout
      - run:
          name: Build image, test it, tag it, publish it
          command: |
            echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
            ./build_test_publish.sh
            docker logout

workflows:
  version: 2
  build-publish-deploy:
    jobs:
      - build-publish:
          context: cyberdojo-tools-context
          filters:
            branches:
              only: [ master ]
